<?php require_once "templates/header.phtml"; ?>

<h1>Álbumes</h1>

<!-- Acceso restringido para la inserción de bandas -->
<?php 
//if (!isset($_SESSION['USER_ID'])) {
    require_once "templates/album_form_add.phtml";
//}
?>

<!-- Acceso público -->
<table class="table mb-5 mt-5">
    <thead>
        <tr>
            <th>Título</th>
            <th>Año</th>
            <th>Banda</th>
            
            <?php // if (!isset($_SESSION['USER_ID'])) : ?>
            <th></th>
            <?php // endif; ?>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($albums as $album) : ?>
            <tr>
                <td>
                    <a class="link-dark" href="./album/<?= $album->id ?> "><?= $album->title ?></a>
                </td>
                <td><?= $album->year ?></td>
                <td><?= $album->band_id ?></td>

                <!-- Acceso restringido para la modificación/eliminación de bandas -->
                <?php // if (!isset($_SESSION['USER_ID'])) : ?>
                <td>
                    <a class="link-dark" href="./edit-album/<?= $album->id ?>">Editar</a> | 
                    <a class="link-dark" href="./delete-album/<?= $album->id ?>">Eliminar</a>
                </td>
                <?php // endif; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="d-flex justify-content-center align-items-center">
    <a href="./">Volver</a>
</div>

<?php require_once "templates/footer.phtml"; ?>