<?php require_once "templates/header.phtml"; ?>

<h1>Editar <?= $album->title ?></h1>

<form action="edit-album/<?= $album->id ?>" method="POST">
    <input type="text" name="title" value="<?= $album->title ?>" placeholder="Titulo" require>
    <input type="text" name="year" value="<?= $album->year ?>" placeholder="Año de creación" require>
    <select name="band_id" require>
        <!-- Se muestra el nombre de cada banda en el select -->
        <?php foreach ($bands as $band) : ?>
            <?php if ($band->id == $currentBand->id) : ?>
                <option value="<?= $band->id ?>" selected><?= $band->name ?></option>
            <?php else : ?>
                <option value="<?= $band->id ?>"><?= $band->name ?></option>
            <?php endif; ?>
        <?php endforeach; ?>
    </select>
    <button type="submit">Listo</button>
</form>

<div class="d-flex justify-content-center align-items-center">
    <a href="./albums">Volver</a>
</div>

<?php require_once "templates/footer.phtml"; ?>