<?php require_once "templates/header.phtml"; ?>

<h1>Álbumes</h1>

<!-- Acceso restringido para la inserción de bandas -->
<?php 
if (!isset($_SESSION['USER_ID'])) {
    require_once "templates/album_form_add.phtml";
}
?>

<!-- Acceso público -->
<ul class="list-group mt-5 mb-5">
    <?php foreach ($albums as $album) : ?>
        <li class="list-group-item d-flex justify-content-between">
            <div>
                <a class="link-dark" href="./album/<?= $album->id ?> "><?= $album->title ?></a>
            </div>
            <?php if (!isset($_SESSION['USER_ID'])) : ?>
                <div class="d-flex justify-content-end">
                    <a href="./edit-album/<?= $album->id ?>" type="btn" class='btn btn-outline-secondary'>Editar</a>
                    <a href="./delete-album/<?= $album->id ?>" type="btn" class='btn btn-outline-danger ms-2'>Eliminar</a>
                </div>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ul>

<div class="d-flex justify-content-center align-items-center">
    <a href="./">Volver</a>
</div>

<?php require_once "templates/footer.phtml"; ?>