<?php require_once "templates/header.phtml"; ?>

<div class="card mb-5">
    <h1 class="card-header"><?= $album->title ?></h1>
    <div class="card-body">
        <p>Año de lanzamiento: <span><?= $album->year ?></span></p>
        <p>Banda: <span><?= $band->name ?></span></p>
    </div>
</div>

<div class="d-flex justify-content-center align-items-center">
    <a href="./">Volver</a>
</div>

<?php require_once "templates/footer.phtml"; ?>