<?php require_once "templates/header.phtml"; ?>

<h1>Editar <?= $album->title ?></h1>

<form action="edit-album/<?= $album->id ?>" method="POST">
    <input type="text" name="title" value="<?= $album->title ?>" placeholder="Titulo" require>
    <input type="text" name="year" value="<?= $album->year ?>" placeholder="Año de creación" require>
    <select name="band_id" requiered>
        <!-- Se muestra el nombre de cada banda en el select -->
        <?php foreach ($bands as $band) : ?>
            <option value="<?= $band->id ?>"><?= $band->name ?></option>
        <?php endforeach; ?>
    </select>
    <button type="submit">Listo</button>
</form>

<div class="d-flex justify-content-center align-items-center">
    <a href="./albums">Volver</a>
</div>

<?php require_once "templates/footer.phtml"; ?>