<div class="d-flex justify-content-center align-items-center mt-4">
    <form action="add-band" method="POST">
        <input type="text" name="name" placeholder="Nombre" required>
        <input type="text" name="genre" placeholder="Género" required>
        <input type="text" name="location" placeholder="Ciudad de origen" require>
        <input type="number" name="year" placeholder="Año de creación" require>
        <button type="submit">Insertar</button>
    </form>
</div>