<?php require_once "templates/header.phtml"; ?>

<h1>Bandas</h1>

<!-- Acceso restringido para la inserción de bandas -->
<?php // if (!isset($_SESSION['USER_ID'])) : ?>
    <div class="d-flex justify-content-center align-items-center mt-4">
        <form action="add-band" method="POST">
            <input type="text" name="name" placeholder="Nombre" required>
            <input type="text" name="genre" placeholder="Género" required>
            <input type="text" name="country" placeholder="País de origen" require>
            <input type="number" name="year" placeholder="Año de creación" require>
            <button type="submit">Insertar</button>
        </form>
    </div>
<?php // endif; ?>

<!-- Acceso público -->
<table class="table mb-5 mt-5">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Género</th>
            <th>País de origen</th>
            <th>Año de creación</th>
            
            <?php // if (!isset($_SESSION['USER_ID'])) : ?>
            <th></th>
            <?php // endif; ?>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($bands as $band) : ?>
            <tr>
                <td>
                    <a class="link-dark" href="./band/<?= $band->id ?> "><?= $band->name ?></a>
                </td>
                <td><?= $band->genre ?></td>
                <td><?= $band->formed_country ?></td>
                <td><?= $band->formed_year ?></td>

                <!-- Acceso restringido para la modificación/eliminación de bandas -->
                <?php // if (!isset($_SESSION['USER_ID'])) : ?>
                <td>
                    <a class="link-dark" href="./edit-band/<?= $band->id ?>">Editar</a> | 
                    <a class="link-dark" href="./delete-band/<?= $band->id ?>">Eliminar</a>
                </td>
                <?php // endif; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="d-flex justify-content-center align-items-center">
    <a href="./">Volver</a>
</div>

<?php require_once "templates/footer.phtml"; ?>