<?php require_once "templates/header.phtml"; ?>

<div class="card">
    <h1 class="card-header"><?= $band->name ?></h1>
    <div class="card-body">
        <p>Género: <span><?= $band->genre ?></span></p>
        <p>País de origen: <span><?= $band->formed_country ?></span></p>
        <p>Año de creación: <span><?= $band->formed_year ?></span></p>

        <h2>Álbumes</h2>
        <table>
            <thead>
                <tr>
                    <th>Álbum</th>
                    <th>Año de lanzamiento</th>
                </tr>
            </thead>

            <?php foreach ($albums as $album) : ?>
                <td>
                    <a href="album/<?= $album->id ?>"><?= $album->title ?></a>
                </td>
                <td><?= $album->year ?></td>
            <?php endforeach; ?>
        </table>
    </div>
</div>

<div class="d-flex justify-content-center align-items-center">
    <a href="./bands">Volver</a>
</div>

<?php require_once "templates/footer.phtml"; ?>