    </main>

    <footer class="d-flex flex-wrap justify-content-center align-items-center py-3 my-2 border-top">
        <div class="align-items-center">
            <span class="text-muted">LocalSoundTandil &copy; 2023 | Todos los derechos reservados</span>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>

</html>