<?php require_once "header.phtml"; ?>

<div class="container w-100">
    <div class="row">
        <div class="col-xl-6 pe-5 text-justify">
            <h1><?= APP_NAME ?></h1>
            <p class="text-justify">Nuestra página web busca crear un espacio de encuentro entre músicos y seguidores de la música de la provincia de Buenos Aires, proporcionando información sobre próximos conciertos, perfiles detallados de bandas y artistas, y la posibilidad de escuchar su música. Además, nos esforzamos por mantener a la comunidad informada sobre eventos musicales, festivales y oportunidades para apoyar a las bandas locales. <?= APP_NAME ?> es la plataforma ideal para explorar la riqueza musical de la región, celebrar la creatividad local y construir puentes que fortalezcan la escena musical bonaerense.</p>
            <p>¡Unite a nosotros para dar vida a la música de Buenos Aires!</p>
        </div>
    
        <div class="col-xl-6 img-container">
            <img src="img/concert_01.jpg" alt="Recital de rock">
        </div>
    </div>
</div>



<?php require_once "footer.phtml"; ?>