<?php require_once "header.phtml"; ?>

<div class="container w-100">
    <div class="row">
        <div class="col-lg-6 pe-5 text-justify">
            <h1>LocalSoundTandil</h1>
            <p class="text-justify">Nuestra página web busca crear un espacio de encuentro entre músicos y seguidores de la música local, proporcionando información sobre próximos conciertos, perfiles detallados de bandas y artistas, y la posibilidad de escuchar su música. Además, nos esforzamos por mantener a la comunidad informada sobre eventos musicales, festivales y oportunidades para apoyar a las bandas locales. LocalSoundTandil es la plataforma ideal para explorar la riqueza musical de la región, celebrar la creatividad local y construir puentes que fortalezcan la escena musical tandilense.</p>
            <p>¡Unite a nosotros en este emocionante viaje para dar vida a la música de Tandil!</p>
        </div>
    
        <div class="col-lg-6 img-container">
            <img src="img/tandil_01.jpg" alt="Plaza San Martín">
        </div>
    </div>
</div>



<?php require_once "footer.phtml"; ?>